const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Product = require('./models/Product');
const Coupon = require('./models/Coupon');
const Category = require('./models/Category');

dotenv.config();

const productsData = [
  // Required exact 15 products with exact prices
  {
    name: 'Glow Perfect Primer',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Silky smooth pore-blurring face primer for long-lasting radiant makeup.',
    price: 599,
    originalPrice: 799,
    stock: 25,
    SKU: 'DMG-BTY-001',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800'],
    rating: 4.8,
    reviewCount: 142,
    benefits: ['Blurs pores instantly', 'Hydrating formula', 'Extends makeup wear up to 16h'],
    ingredients: 'Dimethicone, Silica, Tocopherol (Vitamin E), Hyaluronic Acid.',
    howToUse: 'Smooth a small drop evenly over clean skin before foundation application.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Open Pores', 'Uneven Texture', 'Dryness'],
    skinType: 'All'
  },
  {
    name: 'Flawless Finish Foundation',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Lightweight buildable medium-to-full coverage liquid foundation with SPF 20.',
    price: 899,
    originalPrice: 1199,
    stock: 30,
    SKU: 'DMG-BTY-002',
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800'],
    rating: 4.7,
    reviewCount: 98,
    benefits: ['Natural satin finish', 'Non-comedogenic', 'Transfer-resistant'],
    ingredients: 'Water, Cyclopentasiloxane, Titanium Dioxide, Niacinamide, Glycerin.',
    howToUse: 'Apply 1-2 pumps onto face using a makeup sponge or foundation brush.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Uneven Tone', 'Pigmentation', 'Acne Marks'],
    skinType: 'Combination'
  },
  {
    name: 'HD Concealer',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'High-definition full coverage liquid concealer for dark circles and spots.',
    price: 499,
    originalPrice: 649,
    stock: 18,
    SKU: 'DMG-BTY-003',
    images: ['https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=800'],
    rating: 4.6,
    reviewCount: 85,
    benefits: ['Crease-proof', 'Dark circle eraser', 'Crease-free matte finish'],
    ingredients: 'Aqua, Isododecane, Glycerin, Caffeine Extract, Vitamin E.',
    howToUse: 'Dot under eyes and over blemishes. Blend outwards gently.',
    featured: false,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Dark Circles', 'Blemishes', 'Fine Lines'],
    skinType: 'All'
  },
  {
    name: 'Soft Matte Compact Powder',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Oil-control pressed powder for a soft-focus matte perfection all day.',
    price: 399,
    originalPrice: 499,
    stock: 40,
    SKU: 'DMG-BTY-004',
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800'],
    rating: 4.5,
    reviewCount: 64,
    benefits: ['Shine control for 8h', 'Ultra-light texture', 'Sun protection SPF 15'],
    ingredients: 'Talc, Mica, Zinc Oxide, Vitamin E, Rosemary Extract.',
    howToUse: 'Dust lightly over face using puff or powder brush to set makeup.',
    featured: false,
    bestSeller: false,
    newArrival: false,
    skinConcerns: ['Oily Skin', 'Shine', 'Open Pores'],
    skinType: 'Oily'
  },
  {
    name: 'Rosy Glow Blush',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Silky smooth powder blush delivering a flush of healthy rosy color.',
    price: 449,
    originalPrice: 599,
    stock: 22,
    SKU: 'DMG-BTY-005',
    images: ['https://images.unsplash.com/photo-1599733589046-9b8308b5b50d?w=800'],
    rating: 4.9,
    reviewCount: 110,
    benefits: ['Highly pigmented', 'Blendable formula', 'Natural glow finish'],
    ingredients: 'Mica, Magnesium Stearate, Jojoba Seed Oil, Rosehip Oil.',
    howToUse: 'Sweep onto apples of cheeks using a fluffy blush brush.',
    featured: true,
    bestSeller: true,
    newArrival: true,
    skinConcerns: ['Dullness'],
    skinType: 'All'
  },
  {
    name: 'Golden Hour Highlighter',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Luminous champagne gold powder highlighter for intense glass skin shine.',
    price: 549,
    originalPrice: 749,
    stock: 15,
    SKU: 'DMG-BTY-006',
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800'],
    rating: 4.8,
    reviewCount: 92,
    benefits: ['Blinding golden shimmer', 'Zero chunky glitter', 'Long-wearing luminous glow'],
    ingredients: 'Synthetic Fluorphlogopite, Mica, Pearl Powder, Vitamin E.',
    howToUse: 'Apply to high points of face: cheekbones, nose tip, Cupid\'s bow.',
    featured: true,
    bestSeller: false,
    newArrival: true,
    skinConcerns: ['Dullness'],
    skinType: 'All'
  },
  {
    name: 'Nude Eyeshadow Palette',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: '12 versatile warm nude matte and shimmer shades for everyday glam.',
    price: 699,
    originalPrice: 899,
    stock: 20,
    SKU: 'DMG-BTY-007',
    images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800'],
    rating: 4.7,
    reviewCount: 130,
    benefits: ['Rich color payoff', 'Zero fallout', 'Blendable formulas'],
    ingredients: 'Mica, Talc, Mineral Oil, Squalane, Tocopherol.',
    howToUse: 'Apply lighter shades on eyelid and deeper colors in crease to define.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Intense Black Eyeliner',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Waterproof felt-tip liquid eyeliner pen for precise cat-eye flicks.',
    price: 299,
    originalPrice: 399,
    stock: 50,
    SKU: 'DMG-BTY-008',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800'],
    rating: 4.6,
    reviewCount: 175,
    benefits: ['24h smudge-proof', 'Ultra-fine 0.1mm tip', 'Quick dry jet black finish'],
    ingredients: 'Aqua, Acrylates Copolymer, Carbon Black, Propylene Glycol.',
    howToUse: 'Glid tip along lash line from inner to outer corner.',
    featured: false,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Volume Boost Mascara',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Dramatic volume and lash lengthening mascara with hourglass wand.',
    price: 449,
    originalPrice: 599,
    stock: 35,
    SKU: 'DMG-BTY-009',
    images: ['https://images.unsplash.com/photo-1560700146-81cf38883584?w=800'],
    rating: 4.7,
    reviewCount: 105,
    benefits: ['Zero clumping', 'Clump-free volume', 'Castor oil lash nourishment'],
    ingredients: 'Beeswax, Carnauba Wax, Iron Oxides, Castor Oil, Keratin.',
    howToUse: 'Wiggle brush from base to tip of lashes in zig-zag motion.',
    featured: false,
    bestSeller: false,
    newArrival: true,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Waterproof Kajal',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Deep black kohl pencil infused with Almond Oil and Aloe Vera.',
    price: 249,
    originalPrice: 349,
    stock: 60,
    SKU: 'DMG-BTY-010',
    images: ['https://images.unsplash.com/photo-1583241799056-e2d304956d4c?w=800'],
    rating: 4.8,
    reviewCount: 210,
    benefits: ['Soothes sensitive eyes', '16h stay', 'Smudge-resistant'],
    ingredients: 'Almond Oil, Aloe Vera Extract, Carbon Black, Vitamin E.',
    howToUse: 'Glide along waterline and lash line for intense eye definition.',
    featured: false,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Sensitivity'],
    skinType: 'Sensitive'
  },
  {
    name: 'Velvet Matte Lipstick',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Rich bullet lipstick delivering comfortable plush velvet matte color.',
    price: 499,
    originalPrice: 649,
    stock: 28,
    SKU: 'DMG-BTY-011',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800'],
    rating: 4.9,
    reviewCount: 188,
    benefits: ['Non-drying formula', 'One-swipe full coverage', 'Enriched with Shea Butter'],
    ingredients: 'Shea Butter, Argan Oil, Macadamia Seed Oil, Red Pigments.',
    howToUse: 'Apply directly onto lips starting from center to outer edges.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Dryness'],
    skinType: 'All'
  },
  {
    name: 'Hydrating Lip Gloss',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Non-sticky high-shine lip gloss infused with Hyaluronic Acid & Coconut Oil.',
    price: 399,
    originalPrice: 499,
    stock: 30,
    SKU: 'DMG-BTY-012',
    images: ['https://images.unsplash.com/photo-1591360236480-4ed861025fa1?w=800'],
    rating: 4.6,
    reviewCount: 77,
    benefits: ['Glass-like shine', 'Plumping effect', 'Ultra hydrating'],
    ingredients: 'Polybutene, Coconut Oil, Hyaluronic Acid, Vanilla Flavor.',
    howToUse: 'Wear alone or layer over your favorite lip color for extra gloss.',
    featured: false,
    bestSeller: false,
    newArrival: true,
    skinConcerns: ['Dryness'],
    skinType: 'Dry'
  },
  {
    name: 'Lip & Cheek Tint',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Multi-use natural flush tint for lips, cheeks, and eyelids.',
    price: 449,
    originalPrice: 599,
    stock: 25,
    SKU: 'DMG-BTY-013',
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800'],
    rating: 4.8,
    reviewCount: 124,
    benefits: ['Dewy natural finish', 'Blendable gel formula', 'Hydrating beetroot extract'],
    ingredients: 'Water, Beetroot Root Extract, Glycerin, Rose Extract.',
    howToUse: 'Dab small dots on lips and cheeks. Blend swiftly with fingertips.',
    featured: true,
    bestSeller: true,
    newArrival: true,
    skinConcerns: ['Dullness'],
    skinType: 'All'
  },
  {
    name: 'Makeup Fixer Setting Spray',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Makeup',
    description: 'Hydrating setting mist that locks in makeup for 24h with Green Tea.',
    price: 599,
    originalPrice: 799,
    stock: 20,
    SKU: 'DMG-BTY-014',
    images: ['https://images.unsplash.com/photo-1608248597261-83325805435f?w=800'],
    rating: 4.7,
    reviewCount: 95,
    benefits: ['Sweat and humidity proof', 'Soothing Green Tea', 'Zero melt makeup setting'],
    ingredients: 'Aqua, Green Tea Leaf Extract, Niacinamide, PVP, Chamomile.',
    howToUse: 'Hold bottle 8-10 inches away and mist face in an X and T shape.',
    featured: false,
    bestSeller: false,
    newArrival: false,
    skinConcerns: ['Oily Skin', 'Makeup Melting'],
    skinType: 'All'
  },
  {
    name: 'Professional Makeup Brush Set',
    brand: 'DM-GLOWCART Beauty',
    category: 'Beauty & Personal Care',
    subcategory: 'Tools',
    description: '10-piece ultra-soft synthetic cruelty-free brush collection with pouch.',
    price: 799,
    originalPrice: 1199,
    stock: 15,
    SKU: 'DMG-BTY-015',
    images: ['https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=800'],
    rating: 4.9,
    reviewCount: 160,
    benefits: ['Zero hair shedding', 'Ergonomic wooden handles', 'Includes travel pouch'],
    ingredients: 'Synthetic Taklon Fibers, Aluminum Ferrule, Wood.',
    howToUse: 'Use specific brushes for foundation, powder, eyeshadow, and blending.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },

  // Expanded Fashion Products (covering range 599-1000)
  {
    name: 'Floral Print Rayon Tunic Top',
    brand: 'GLOW FASHION',
    category: 'Fashion',
    subcategory: 'Western Wear',
    description: 'Chic printed tunic top with mandarin collar and 3/4 sleeves.',
    price: 699,
    originalPrice: 999,
    stock: 25,
    SKU: 'DMG-FSH-041',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800'],
    rating: 4.7,
    reviewCount: 62,
    benefits: ['Soft Rayon Fabric', 'Breathable summer wear'],
    ingredients: '100% Viscose Rayon.',
    howToUse: 'Pair with jeans or trousers.',
    featured: true,
    bestSeller: true,
    newArrival: true,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Cotton Blend Straight Kurti - Coral Pink',
    brand: 'GLOW FASHION',
    category: 'Fashion',
    subcategory: 'Ethnic Wear',
    description: 'Comfortable daily wear straight kurti with delicate neck embroidery.',
    price: 799,
    originalPrice: 1199,
    stock: 30,
    SKU: 'DMG-FSH-042',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800'],
    rating: 4.8,
    reviewCount: 94,
    benefits: ['Side slits for comfort', 'Colorfast dyes'],
    ingredients: 'Cotton Blend.',
    howToUse: 'Machine wash cold.',
    featured: false,
    bestSeller: true,
    newArrival: true,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Oversized Silk Blend Shirt - Rose Gold',
    brand: 'GLOW FASHION',
    category: 'Fashion',
    subcategory: 'Western Wear',
    description: 'Chic oversized satin button-down shirt ideal for casual and party styling.',
    price: 899,
    originalPrice: 1499,
    stock: 18,
    SKU: 'DMG-FSH-026',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800'],
    rating: 4.6,
    reviewCount: 52,
    benefits: ['Lustrous satin finish', 'Comfortable relaxed silhouette'],
    ingredients: 'Satin Silk Polyester Blend.',
    howToUse: 'Tuck into denim jeans or style with tailored trousers.',
    featured: true,
    bestSeller: false,
    newArrival: true,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Printed Georgette Scarf & Crop Top Set',
    brand: 'GLOW FASHION',
    category: 'Fashion',
    subcategory: 'Western Wear',
    description: 'Trendy crop top with matching lightweight georgette scarf.',
    price: 649,
    originalPrice: 899,
    stock: 20,
    SKU: 'DMG-FSH-043',
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800'],
    rating: 4.5,
    reviewCount: 38,
    benefits: ['Stretchable fit', 'Trendy pastel floral print'],
    ingredients: 'Poly Georgette.',
    howToUse: 'Hand wash recommended.',
    featured: false,
    bestSeller: false,
    newArrival: true,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Floral Print Cotton Anarkali Kurta',
    brand: 'GLOW FASHION',
    category: 'Fashion',
    subcategory: 'Ethnic Wear',
    description: 'Elegant handcrafted breathable cotton flared Anarkali kurta with dupatta set.',
    price: 1299,
    originalPrice: 1999,
    stock: 15,
    SKU: 'DMG-FSH-024',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800'],
    rating: 4.8,
    reviewCount: 88,
    benefits: ['100% Pure Premium Cotton', 'Vibrant colorfast dyes', 'All day comfort fit'],
    ingredients: '100% Cotton Linen.',
    howToUse: 'Pair with leggings or palazzos for festive or casual occasions.',
    featured: true,
    bestSeller: true,
    newArrival: true,
    skinConcerns: [],
    skinType: 'All'
  },

  // Additional Skincare & Beauty
  {
    name: 'Vitamin C Radiance Face Serum',
    brand: 'GLOW SKIN LABS',
    category: 'Beauty & Personal Care',
    subcategory: 'Skincare',
    description: '15% L-Ascorbic Acid face serum with Ferulic Acid for glowing brightened skin.',
    price: 649,
    originalPrice: 899,
    stock: 35,
    SKU: 'DMG-SKN-016',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800'],
    rating: 4.8,
    reviewCount: 230,
    benefits: ['Fades dark spots', 'Boosts collagen', 'Fights free radicals'],
    ingredients: '15% Pure Vitamin C, Ferulic Acid, Hyaluronic Acid, Vitamin E.',
    howToUse: 'Apply 3-4 drops morning and night before moisturization.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Dullness', 'Pigmentation', 'Uneven Tone'],
    skinType: 'All'
  },
  {
    name: 'Hyaluronic Acid Gel Moisturizer',
    brand: 'GLOW SKIN LABS',
    category: 'Beauty & Personal Care',
    subcategory: 'Skincare',
    description: 'Lightweight oil-free water gel moisturizer offering 72h continuous hydration.',
    price: 549,
    originalPrice: 749,
    stock: 45,
    SKU: 'DMG-SKN-017',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'],
    rating: 4.7,
    reviewCount: 180,
    benefits: ['Plumps fine lines', 'Oil-free gel feel', '72h hydration burst'],
    ingredients: 'Hyaluronic Acid, Ceramides, Aloe Vera Extract, Trehalose.',
    howToUse: 'Smooth over face and neck morning and evening.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Dryness', 'Dehydration', 'Fine Lines'],
    skinType: 'Dry'
  },
  {
    name: 'Niacinamide 10% Blemish Serum',
    brand: 'GLOW SKIN LABS',
    category: 'Beauty & Personal Care',
    subcategory: 'Skincare',
    description: 'Clear skin formula with 10% Niacinamide and 1% Zinc PCA to target breakouts.',
    price: 499,
    originalPrice: 699,
    stock: 38,
    SKU: 'DMG-SKN-018',
    images: ['https://images.unsplash.com/photo-1608248597261-83325805435f?w=800'],
    rating: 4.8,
    reviewCount: 290,
    benefits: ['Controls excess sebum', 'Minimizes pore appearance', 'Reduces acne marks'],
    ingredients: '10% Niacinamide, 1% Zinc PCA, Hyaluronic Acid.',
    howToUse: 'Apply a few drops after cleansing, before heavy creams.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Acne', 'Oily Skin', 'Open Pores'],
    skinType: 'Oily'
  },
  {
    name: 'Pure Rose Water Facial Mist',
    brand: 'GLOW SKIN LABS',
    category: 'Beauty & Personal Care',
    subcategory: 'Skincare',
    description: '100% pure steam-distilled Kannauj rose water toner and refreshing facial spray.',
    price: 349,
    originalPrice: 449,
    stock: 50,
    SKU: 'DMG-SKN-019',
    images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=800'],
    rating: 4.9,
    reviewCount: 315,
    benefits: ['Maintains skin pH', 'Instantly calms redness', '100% natural formula'],
    ingredients: '100% Pure Steam Distilled Damask Rose Water.',
    howToUse: 'Mist liberally over face whenever skin feels dry or fatigued.',
    featured: false,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Redness', 'Sensitivity', 'Dullness'],
    skinType: 'Sensitive'
  },
  {
    name: 'Gentle Foaming Cleansing Milk',
    brand: 'GLOW SKIN LABS',
    category: 'Beauty & Personal Care',
    subcategory: 'Skincare',
    description: 'Sulfate-free hydrating cleanser infused with Centella and Green Tea.',
    price: 399,
    originalPrice: 549,
    stock: 28,
    SKU: 'DMG-SKN-020',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'],
    rating: 4.6,
    reviewCount: 94,
    benefits: ['Zero skin tight feeling', 'Removes light makeup & dirt', 'Soothes barrier'],
    ingredients: 'Centella Asiatica, Green Tea Extract, Glycerin, Oat Kernel Extract.',
    howToUse: 'Massage onto damp skin for 60 seconds then rinse with lukewarm water.',
    featured: false,
    bestSeller: false,
    newArrival: true,
    skinConcerns: ['Sensitivity', 'Dryness'],
    skinType: 'Sensitive'
  },

  // Accessories
  {
    name: 'Vegan Leather Tote Bag - Nude Pink',
    brand: 'GLOW ACCESSORIES',
    category: 'Accessories',
    subcategory: 'Bags',
    description: 'Spacious everyday tote bag with laptop sleeve and gold zip hardware.',
    price: 1199,
    originalPrice: 1799,
    stock: 20,
    SKU: 'DMG-ACC-027',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800'],
    rating: 4.9,
    reviewCount: 115,
    benefits: ['Fits 15-inch laptop', 'Premium cruelty-free vegan leather', 'Water-resistant interior'],
    ingredients: 'Premium PU Vegan Leather.',
    howToUse: 'Wipe clean with soft damp cloth.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: '18K Gold Plated Hoop Earrings',
    brand: 'GLOW ACCESSORIES',
    category: 'Accessories',
    subcategory: 'Jewelry',
    description: 'Hypoallergenic classic thick gold hoops for effortless daily elegance.',
    price: 599,
    originalPrice: 899,
    stock: 25,
    SKU: 'DMG-ACC-028',
    images: ['https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800'],
    rating: 4.8,
    reviewCount: 98,
    benefits: ['Tarnish-free 18K plating', 'Hypoallergenic lead/nickel free', 'Ultra lightweight'],
    ingredients: 'Stainless Steel with 18K Gold PVD Coating.',
    howToUse: 'Store in airtight pouch. Avoid direct contact with perfume spray.',
    featured: false,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Pure Mulberry Silk Scrunchie Set of 3',
    brand: 'GLOW ACCESSORIES',
    category: 'Accessories',
    subcategory: 'Hair Accessories',
    description: '100% 22 Momme Mulberry silk hair elastics that prevent creasing and hair breakage.',
    price: 499,
    originalPrice: 699,
    stock: 35,
    SKU: 'DMG-ACC-029',
    images: ['https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800'],
    rating: 4.9,
    reviewCount: 154,
    benefits: ['Prevents hair split ends & tangles', 'Zero crease marks', 'Luxurious silk shine'],
    ingredients: '100% Pure Grade 6A Mulberry Silk.',
    howToUse: 'Wrap twice around ponytail or bun.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },

  // Home & Lifestyle
  {
    name: 'Rose & Vanilla Scented Soy Candle',
    brand: 'GLOW HOME',
    category: 'Home & Lifestyle',
    subcategory: 'Home Fragrance',
    description: 'Hand-poured 100% natural soy wax candle delivering a warm romantic fragrance.',
    price: 549,
    originalPrice: 799,
    stock: 25,
    SKU: 'DMG-HOM-031',
    images: ['https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800'],
    rating: 4.9,
    reviewCount: 130,
    benefits: ['Clean 45h burn time', 'Zero toxic paraffin', 'Relieves stress & anxiety'],
    ingredients: '100% Natural Soy Wax, Essential Oils, Organic Cotton Wick.',
    howToUse: 'Trim wick to 1/4 inch before lighting. Allow wax pool to reach glass edges.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: [],
    skinType: 'All'
  },
  {
    name: 'Rose Quartz Gua Sha & Facial Roller Tool',
    brand: 'GLOW HOME',
    category: 'Home & Lifestyle',
    subcategory: 'Wellness',
    description: 'Natural Rose Quartz crystal facial massage tool for lymphatic drainage.',
    price: 699,
    originalPrice: 999,
    stock: 20,
    SKU: 'DMG-HOM-032',
    images: ['https://images.unsplash.com/photo-1617897903246-719242758050?w=800'],
    rating: 4.8,
    reviewCount: 175,
    benefits: ['Depuffs eye area', 'Enhances serum absorption', 'Contours jawline'],
    ingredients: '100% Authentic Natural Brazilian Rose Quartz.',
    howToUse: 'Apply face oil first. Glide tool outward and upward across jawline and cheeks.',
    featured: true,
    bestSeller: true,
    newArrival: false,
    skinConcerns: ['Fine Lines', 'Dullness'],
    skinType: 'All'
  }
];

const seedDatabase = async () => {
  const uri = process.env.MONGO_URI || 'mongodb+srv://Monisha:monisha123@cluster0.nfpi4z1.mongodb.net/dm-glowcart?retryWrites=true&w=majority';

  try {
    console.log('Connecting to your personal MongoDB Atlas Cluster...');
    await mongoose.connect(uri, { serverSelectionTimeoutMS: 10000 });
    console.log('Connected to MongoDB Atlas Cluster successfully!');

    // Clear existing data
    await User.deleteMany({});
    await Product.deleteMany({});
    await Coupon.deleteMany({});
    await Category.deleteMany({});

    console.log('Cleared existing database collections.');

    // Seed Admin User
    const adminUser = await User.create({
      name: 'DM-GLOWCART Admin',
      email: 'admin@glowcart.com',
      password: 'Admin@123',
      role: 'ADMIN',
      phone: '+91 9876543210',
      isActive: true
    });
    console.log(`Created Admin User: ${adminUser.email}`);

    // Seed Standard Demo User
    const demoUser = await User.create({
      name: 'Monisha User',
      email: 'user@glowcart.com',
      password: 'User@123',
      role: 'USER',
      phone: '+91 9876543211',
      isActive: true
    });
    console.log(`Created Demo User: ${demoUser.email}`);

    // Seed Categories
    const categoriesData = [
      {
        name: 'Beauty & Personal Care',
        slug: 'beauty-personal-care',
        description: 'Premium cosmetics, skincare serums, and grooming tools.',
        image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800'
      },
      {
        name: 'Fashion',
        slug: 'fashion',
        description: 'Chic ethnic wear, sarees, tops, and stylish apparel.',
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800'
      },
      {
        name: 'Accessories',
        slug: 'accessories',
        description: 'Vegan leather totes, 18K gold plated jewelry, and silk scrunchies.',
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800'
      },
      {
        name: 'Home & Lifestyle',
        slug: 'home-lifestyle',
        description: 'Scented soy candles, facial Gua Sha tools, and cozy satin bedding.',
        image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=800'
      }
    ];

    await Category.insertMany(categoriesData);
    console.log('Created 4 Categories.');

    // Seed Coupons
    const couponsData = [
      {
        code: 'GLOW10',
        discountType: 'PERCENTAGE',
        discountValue: 10,
        minimumOrder: 300,
        maximumDiscount: 200,
        usageLimit: 500,
        expiryDate: new Date('2027-12-31')
      },
      {
        code: 'WELCOME15',
        discountType: 'PERCENTAGE',
        discountValue: 15,
        minimumOrder: 500,
        maximumDiscount: 350,
        usageLimit: 300,
        expiryDate: new Date('2027-12-31')
      },
      {
        code: 'BEAUTY20',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        minimumOrder: 999,
        maximumDiscount: 500,
        usageLimit: 200,
        expiryDate: new Date('2027-12-31')
      }
    ];

    await Coupon.insertMany(couponsData);
    console.log('Created 3 Coupons (GLOW10, WELCOME15, BEAUTY20).');

    // Seed Products
    await Product.insertMany(productsData);
    console.log(`Successfully seeded ${productsData.length} Products into MongoDB!`);

    console.log('\n--- SEEDING COMPLETED SUCCESSFULLY ---');
    console.log('Admin Credentials: admin@glowcart.com / Admin@123');
    console.log('Demo User Credentials: user@glowcart.com / User@123');
    process.exit(0);
  } catch (error) {
    console.error('Error during database seeding:', error.message);
    process.exit(1);
  }
};

seedDatabase();
